title: Kartografie pro geology
description: Materiály ke cvičení z tematické kartografie pro bakaláře geologie
baseurl: "/geocartography"   # změňte podle názvu repa
url: "https://USERNAME.github.io"  # změňte na svůj GitHub účet
lang: cs
theme: minima
markdown: kramdown
permalink: pretty

header_pages:
  - index.md
  - hodnoceni.md
  - data.md
  - arcgis-nastroje.md
  - literatura.md

collections:
  lessons:
    output: true
    permalink: /lessons/:name/
  assignments:
    output: true
    permalink: /assignments/:name/

defaults:
  - scope: {path: "", type: "lessons"}
    values: {layout: page}
  - scope: {path: "", type: "assignments"}
    values: {layout: page}

exclude: [README.md, Gemfile, Gemfile.lock]
