title: "Návody pro studenty"
description: "Materiály k předmětům"
theme: minima

# co se má zobrazovat v horním menu (rozcestník)
header_pages:
  - index.md
  - Geoinformatika/index.md
  - Zpracování dat v GIS/index.md

# volitelné: hezké URL bez .html
permalink: /:path/
